// <auto-generated />
namespace _05_Photographers_Albums.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSharedAlbums : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSharedAlbums));
        
        string IMigrationMetadata.Id
        {
            get { return "201703121408591_AddSharedAlbums"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
