// <auto-generated />
namespace _03_Sales_Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Problem3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Problem3));
        
        string IMigrationMetadata.Id
        {
            get { return "201703070054361_Problem3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
